version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tds-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: test_data
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Shanghai
    ports:
      - "13306:3305"
    volumes:
      - ./persistent-data/mysql:/var/lib/mysql
      - ./mysql/initsql:/docker-entrypoint-initdb.d
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - traffic-data-system-dev-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tds-redis
    restart: always
    command: redis-server --appendonly yes --port 6380
    ports:
      - "16379:6380"
    volumes:
      - ./persistent-data/redis:/data
    networks:
      - traffic-data-system-dev-net
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tds-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./persistent-data/rabbitmq:/var/lib/rabbitmq
    networks:
      - traffic-data-system-dev-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    image: myapp-backend:latest
    container_name: tds-backend
    restart: always
    expose:
    - "8082"
    ports:
      - "8082:8082"
    env_file:
      - .env
    volumes:
      - ./persistent-data/export:/data/export
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6380
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - traffic-data-system-dev-net

  nginx:
    image: tds-nginx:latest
    container_name: tds-nginx
    restart: always
    build:
      context: ./nginx  # 关键修改：指定构建上下文为 nginx 目录
      dockerfile: Dockerfile
    ports:
      - "19203:19203"
    depends_on:
      - backend
    networks:
      - traffic-data-system-dev-net

networks:
  traffic-data-system-dev-net:
    driver: bridge
